---
- name: Start gitea Server
  block:
  - name: Create gitea directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: "0755"
    with_items:
      - "{{ gitea_dir }}"
      - "{{ gitea_dir }}/data"
      - "{{ gitea_dir }}/config"
      - "{{ gitea_dir }}/postgres"

  - name: Template docker compose file
    ansible.builtin.template:
      src: docker-compose.yml.j2
      dest: "{{ gitea_dir }}/docker-compose.yml"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: "0644"

  - name: gitea Docker Container
    community.docker.docker_compose:
      project_src: "{{ gitea_dir }}"
      state: present
  when: gitea_enabled is true

- name: Stop gitea Server
  block:
    - name: Stop gitea Server
      community.docker.docker_compose:
        project_src: "{{ gitea_dir }}"
        state: absent
  when: gitea_enabled is false
