---
collections:
#   - name: victoriametrics.cluster
#     version: 0.41.0

#   - name: community.mysql
#     version: 3.7.2

  - name: prometheus.prometheus
    version: 0.6.0

  # - name: githubixx.ansible_role_wireguard
  #   version: 14.0.0

roles:
  - name: geerlingguy.mysql
    version: 4.3.3

  - name: geerlingguy.redis
    version: 1.8.0

  - name: geerlingguy.docker
    version: 6.2.0

  - name: geerlingguy.ntp
    version: 2.3.3

  - name: geerlingguy.jenkins
    version: 5.0.1
