---
vagrant_enabled: true
wireguard_enabled: false
docker_enabled: true
ntp_timezone: Asia/Shanghai
gitea_enabled: false
# pip_install_packages:
#   - name: docker
#     extra_args: --break-system-packages
#   - name: docker-compose
#     extra_args: --break-system-packages
jenkins_enabled: true
vaultwarden_enabled: true
