---
vagrant_enabled: false
wireguard_enabled: false
loki_enabled: true
docker_enabled: true

# victoriametrics
victoriametrics_enabled: true
victoriametrics_version: "v1.93.1"
victoriametrics_data_dir: "/data/victoria-metrics/"
victoriametrics_retention_period_months: "1"
victoriametrics_host: "192.168.50.4"

n9e_enabled: true

ddns_go_enabled: true

vaultwarden_enabled: true
vaultwarden_allow_signups: false

alist_enabled: true

gitea_enabled: false

photoprism_enabled: true

nextcloud_enabled: true

ntp_timezone: Asia/Shanghai

# ansible-role-jenkins
jenkins_package_state: latest
jenkins_hostname: "jenkins_hostname.{{ cloudflared_tunnel_domain_name}}"
jenkins_plugins:
  - blueocean
  - ssh-credentials
  - ansible
  - git
  - github
jenkins_plugins_state: latest
jenkins_admin_username: admin