---
- name: Start Portainer Agent
  block:
    - name: Portainer Agent Docker Container
      community.docker.docker_container:
        name: portainer_agent
        image: "portainer/agent:{{ portainer_agent_image_version }}"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/var/lib/docker/volumes:/var/lib/docker/volumes"
          - "/etc/timezone:/etc/timezone"
        ports:
          - "{{ portainer_agent_port }}:9001"
        restart_policy: unless-stopped
        # memory: "{{ portainer_memory }}"
  when: portainer_agent_enabled is true

- name: Stop Portainer
  block:
    - name: Stop portainer Agent
      community.docker.docker_container:
        name: portainer_agent
        state: absent
  when: portainer_agent_enabled is false
