---
- name: Start jenkins Server
  block:
  - name: Create jenkins directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: "0755"
    with_items:
      - "{{ jenkins_dir }}"
      - "{{ jenkins_dir }}/jenkins_home"

  - name: Template docker compose file
    ansible.builtin.template:
      src: docker-compose.yml.j2
      dest: "{{ jenkins_dir }}/docker-compose.yml"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: "0644"

  - name: Jenkins Docker Container
    community.docker.docker_compose:
      project_src: "{{ jenkins_dir }}"
      state: present
  when: jenkins_enabled is true

- name: Stop jenkins Server
  block:
    - name: Stop jenkins Server
      community.docker.docker_compose:
        project_src: "{{ jenkins_dir }}"
        state: absent
  when: jenkins_enabled is false
