---
- name: Start Portainer
  block:
    - name: Create Portainer Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"
      with_items:
        - "{{ portainer_data_directory }}"

    - name: Portainer Docker Container
      community.docker.docker_container:
        name: portainer
        image: "portainer/portainer-ce:{{ portainer_image_version }}"
        volumes:
          - "{{ portainer_data_directory }}/data:/data"
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/etc/timezone:/etc/timezone"
        ports:
          - "{{ portainer_port }}:9443"
        restart_policy: unless-stopped
        memory: "{{ portainer_memory }}"
  when: portainer_enabled is true

- name: Stop Portainer
  block:
    - name: Stop portainer
      community.docker.docker_container:
        name: portainer
        state: absent
  when: portainer_enabled is false
