---
- name: Start nextcloud Server
  block:
  - name: Create nextcloud directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: "0755"
    with_items:
      - /data/nextcloud

  - name: nextcloud Docker Container
    community.docker.docker_container:
      name: nextcloud
      image: nextcloud:27.0.2-apache
      env:
        TZ: Asia/Shanghai
        MYSQL_HOST: "{{ mysql_host }}"
        MYSQL_PASSWORD: "{{ mysql_nextcloud_password }}"
        MYSQL_DATABASE: nextcloud
        MYSQL_USER: nextcloud
        REDIS_HOST: "{{ redis_host }}"
        REDIS_HOST_PASSWORD: "{{ redis_requirepass }}"
        NEXTCLOUD_ADMIN_USER: admin
        NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_admin_password }}"
      volumes:
        - "/data/nextcloud/:/var/www/html/"
      networks:
        - name: homelab
      ports:
        - "8080:80"
      restart_policy: always

  - name: nextcloud cron Docker Container
    community.docker.docker_container:
      name: nextcloud-cron
      image: nextcloud:27.0.2-apache
      volumes:
        - "/data/nextcloud/:/var/www/html/"
      entrypoint: /cron.sh
      networks:
        - name: homelab
      restart_policy: always
  when: nextcloud_enabled is true

- name: Stop nextcloud Server
  block:
    - name: Stop nextcloud Server
      community.docker.docker_container:
        name: nextcloud
        state: absent
    - name: Stop nextcloud cron Server
      community.docker.docker_container:
        name: nextcloud-cron
        state: absent
  when: nextcloud_enabled is false
