ingress:
  # - hostname: "echo-server.{{ cloudflared_tunnel_domain_name }}"
  #   service: http://echo-server:8080

  - hostname: "vaultwarden.{{ cloudflared_tunnel_domain_name }}"
    service: http://100.120.83.64:9002

  # - hostname: "vaultwarden.{{ cloudflared_tunnel_domain_name }}/notifications/hub"
  #   service: http://vaultwarden:3012

  # - hostname: "vaultwarden.{{ cloudflared_tunnel_domain_name }}/admin"
  #   service: http://vaultwarden

  # - hostname: "alist.{{ cloudflared_tunnel_domain_name }}"
  #   service: http://alist:5244

  # - hostname: "photoprism.{{ cloudflared_tunnel_domain_name }}"
  #   service: http://100.77.212.44:2342

  - hostname: "jenkins.{{ cloudflared_tunnel_domain_name }}"
    service: http://100.120.83.64:9001

  - service: http_status:404
